### ISSUE TITLE
Unable to distinguish between network errors and api errors?

### ISSUE THREAD

**Issue by antonholmquist** [lionelbarrow/braintree-go#38]
I'm trying determine the failure reason of `bt.Customer().Find(customerID)`.

It returns an error (but not of any exported type) so I can't seem to distinguish between network errors, and the customer not actually existing.

The README states "If Braintree was able to process the request correctly, but was unable to fulfill it due to a semantic failure (such as the credit card being declined) then a `BraintreeError` type is returned.". The problem is that `BraintreeError` doesn't seem to be defined anywhere (just an unexported `braintreeError`), and it's not used for customer find anyways.

Please help me to shed some light on this. Thank you!

**Comment by lionelbarrow** [comment]
Ah, that might be a design bug -- it seems that `BraintreeError` should be exported so that you can check if you've got one.

**Comment by lionelbarrow** [comment]
Fixed in https://github.com/lionelbarrow/braintree-go/commit/41de65ad3d1e7f57fa62f5cfb9941ed1560ddd33

**Comment by antonholmquist** [comment]
`BraintreeError` is now exposed, but `bt.Customer().Find(customerID)´ never returns it, so I still can't distinguish between network errors and the customer not actually existing. The error that is returned is of the unexported type `invalidResponseError`.

**Comment by antonholmquist** [comment]
Shall I post this as a separate issue or will you re-open it?

By the way, do you know if there is any chance that Braintree will accept this as an official Go client in the future?

**Comment by lionelbarrow** [comment]
I'll look into it more.

I'm not sure if this will become an official library any time soon, but I'll pass along the interest.

**Comment by antonholmquist** [comment]
Any news on this?

**Comment by lionelbarrow** [comment]
I took another look at the code this afternoon. As I see it, there are four failure cases to be concerned with:

* A networking failure happens and the request is unable to reach Braintree. It seems unlikely that this would return in a 404. A 502 or 503 is more likely.
* The request reaches Braintree but the URL is wrong. Perhaps we're hitting `GET /merchants/{merchant-id}/castomer` or something like that. In this case Braintree will respond with a 404.
* The request reaches Braintree, hits a valid URL, but the ID in a find request is wrong. For example if we're hitting `GET /merchants/my-merchant/customers/foo-customer` and `foo-customer` does not exist. In this case Braintree with also respond with 404.
* The request reaches Braintree and has nothing wrong with the identifiers, but is wrong for some other reason such has containing an invalid credit card number or a non-sensical charge amount. In this case Braintree will return a 422.

If I understand you correctly, the problem you're having is that you can't distinguish between the second and third case -- is that correct?

If that is the case, my advice would be: assume any 404 is due to an invalid identifier. This library should never allow you to reach an invalid base URL.

**Comment by HongxingTB** [comment]
hi Lionel, currently Customer().Find() return error, do we have a way to distinguish if it's 404 (customer doesn't exist) or 500 without parsing the error string? or get the status code out from error it returned?

**Comment by leighmcculloch** [comment]
Closing because ^
